name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run rustfmt
      run: cargo fmt --all -- --check
    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Build (default features)
      run: cargo build --workspace --all-targets --verbose
    - name: Test (default features)
      run: cargo test --workspace --all-targets --verbose
    - name: Build (all features)
      run: cargo build --workspace --all-targets --all-features --verbose
    - name: Test (all features)
      run: cargo test --workspace --all-targets --all-features --verbose
    - name: Build (no default features)
      run: cargo build --workspace --all-targets --no-default-features --verbose
    - name: Test (no default features)
      run: cargo test --workspace --all-targets --no-default-features --verbose
